import { Product } from './types/Product'

export const sampleProducts: Product[] = [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '../images/p1.jpg',
      price: 170,
      countInStock: 0,
      brand: 'Nike',
      rating: 3,
      numReviews: 5,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '../images/p2.jpg',
      price: 190,
      countInStock: 1,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Pants',
      slug: 'lacoste-free-pants',
      category: 'Pants',
      image: '../images/p3.jpg',
      price: 200,
      countInStock: 1,
      brand: 'Lacoste',
      rating: 5,
      numReviews: 0,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '../images/p4.jpg',
      price: 70,
      countInStock: 3.5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 1,
      description: 'high quality product',
    },
  ]
  